language: go
sudo: false
go:
  - 1.10.x
before_install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
jobs:
  include:
    - script: make all
    - stage: Run Test Coverage
      script: make cover
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Build Release
      script:
        - make release
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/ghb0t-darwin-amd64
          - cross/ghb0t-darwin-amd64.md5
          - cross/ghb0t-darwin-amd64.sha256
          - cross/ghb0t-darwin-386
          - cross/ghb0t-darwin-386.md5
          - cross/ghb0t-darwin-386.sha256
          - cross/ghb0t-freebsd-amd64
          - cross/ghb0t-freebsd-amd64.md5
          - cross/ghb0t-freebsd-amd64.sha256
          - cross/ghb0t-freebsd-386
          - cross/ghb0t-freebsd-386.md5
          - cross/ghb0t-freebsd-386.sha256
          - cross/ghb0t-linux-arm
          - cross/ghb0t-linux-arm.md5
          - cross/ghb0t-linux-arm.sha256
          - cross/ghb0t-linux-arm64
          - cross/ghb0t-linux-arm64.md5
          - cross/ghb0t-linux-arm64.sha256
          - cross/ghb0t-linux-amd64
          - cross/ghb0t-linux-amd64.md5
          - cross/ghb0t-linux-amd64.sha256
          - cross/ghb0t-linux-386
          - cross/ghb0t-linux-386.md5
          - cross/ghb0t-linux-386.sha256
          - cross/ghb0t-solaris-amd64
          - cross/ghb0t-solaris-amd64.md5
          - cross/ghb0t-solaris-amd64.sha256
          - cross/ghb0t-windows-amd64
          - cross/ghb0t-windows-amd64.md5
          - cross/ghb0t-windows-amd64.sha256
          - cross/ghb0t-windows-386
          - cross/ghb0t-windows-386.md5
          - cross/ghb0t-windows-386.sha256
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: "YwhDTdgss2waEAyWO6Db+Th6TCV9feNQem3GLiqzB2082K+fewgHc/4pgRlcFG51ecYl7G/gK/qIBsr3duOsEtdSG0A1DmkF8z1wVo0o2vDetXQM5s6+n6QYa2z6z3ft0zYpIu8C68WzfbcpbYsEU5BUpEuoZrRshB/o/WonCZUnigvMRLRaHgN3z5oXgPUel+sACHvLn/WHSrTZYs1FScWl7rq7AXlPUrOpFp/wShgNVgtSf5W7Yxdxn6VUSvThEKXQnKFam5edPTScDfRT83tXHXzIZES8iOuun5icFcjEzpLBMKPfj3hntB7o8bSZu9pXQONIUbagk0RYbSEWePLE9RMvNnlGKkqoJvjx1i35cDtUfDUDoSGeP4TTxRlKZ6iodZ5vZWC4KXF8xwVfpqfeUfjT/ZiZDBOty8IlQRUR21GUeMnuxRC2u16hU1f8r4CzJpouZZghyk20bO6CJjR0861Tfj782JC0tflu7+DY8AgRq31c8UkwjbVZOYX3yfENzrYIY5JX5H+g4Rm9pah+Fxdgk7mOnCkMc4SDU+QxBFUShTWPPYTuQN1uVEyjNNqEN+l6If+FxI+xnKZYG8WJfpcljHqJRzP3r8fGWYQZvNO0h/85/yph7ihcw6wj5TuPcq0Z1yHBRCFnfBJzpXNY/3jxXCNW9A+Whjrg0qw="
